use_frameworks!

platform :ios, '9.0'

target 'LibOpenFortiVPN-iOS_Example' do
  pod 'LibOpenFortiVPN-iOS', :path => '../'
  pod 'OpenSSL-Universal'

  target 'LibOpenFortiVPN-iOS_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
